---
title: Mecatronica.pe
timezone: America/Lima
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nando.rrb.00@gmail.com
url: "/proyectos"
baseurl: "/proyectos"
description: Desarrollamos prototipos MVP para StartUps y empresarios desde la etapa
  de diseño y manufactura hasta la etapa de masificacion del producto. Tambien brindamos
  servicios de consultoria en ingeniería, y desarrollo de proyectos en general.
skills: Proyectos de Ingenieria - Desarrollo de Prototipos - Generacion de StartUps
meta_author: Fernando Rubio
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Mecatronica del Peru
  location: Lima - Peru
  social: Redes Sociales
  credits: Credits
social:
- title: facebook
  url: https://www.facebook.com/ingenieriamecatronicaperu/
- title: bitbucket
  url: http://bitbucket.org/nandorrb
- title: github
  url: http://github.com/nandorrb
address:
- line: 964484111
- line: Jiron Ciudad Real
- line: Santiago de Surco - Lima
credits: WebPage made using Freelancer, a free to use, open source Bootstrap theme
  created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
markdown: kramdown
permalink: pretty
